name: Lint and Test

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  lint_and_test:
    permissions:
      contents: read
      pull-requests: read

    name: Lint and Test - ${{ matrix.go-version }}
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x, 1.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint package
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Test package
        # comment to run the tests
        run: |
          go test -v ./... -coverprofile=coverage.txt -covermode count
          go tool cover -func coverage.txt
